# loc and iloc

Loc and iloc(Feature Extarction)
Loc: is label base
iloc: is indexbase

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r'D:\ExcelR Data Science\August\Aug 8\players_20.csv')
df

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
0,158023,https://sofifa.com/player/158023/lionel-messi/...,L. Messi,Lionel Andrés Messi Cuccittini,32,24-06-1987,170,72,Argentina,FC Barcelona,...,68+2,66+2,66+2,66+2,68+2,63+2,52+2,52+2,52+2,63+2
1,20801,https://sofifa.com/player/20801/c-ronaldo-dos-...,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,25-06-1987,187,83,Portugal,Juventus,...,65+3,61+3,61+3,61+3,65+3,61+3,53+3,53+3,53+3,61+3
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,26-06-1987,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,27-06-1987,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,28-06-1987,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18273,245006,https://sofifa.com/player/245006/shuai-shao/20...,Shao Shuai,邵帅,22,10-03-1997,186,79,China PR,Beijing Renhe FC,...,43+2,42+2,42+2,42+2,43+2,45+2,46+2,46+2,46+2,45+2
18274,250995,https://sofifa.com/player/250995/mingjie-xiao/...,Xiao Mingjie,Mingjie Xiao,22,01-01-1997,177,66,China PR,Shanghai SIPG FC,...,44+2,43+2,43+2,43+2,44+2,46+2,47+2,47+2,47+2,46+2
18275,252332,https://sofifa.com/player/252332/wei-zhang/20/...,Zhang Wei,张威,19,16-05-2000,186,75,China PR,Hebei China Fortune FC,...,47+2,49+2,49+2,49+2,47+2,47+2,49+2,49+2,49+2,47+2
18276,251110,https://sofifa.com/player/251110/haijian-wang/...,Wang Haijian,汪海健,18,02-08-2000,185,74,China PR,Shanghai Greenland Shenhua FC,...,48+2,48+2,48+2,48+2,48+2,48+2,49+2,49+2,49+2,48+2
18277,233449,https://sofifa.com/player/233449/ximing-pan/20...,Pan Ximing,潘喜明,26,11-01-1993,182,78,China PR,Hebei China Fortune FC,...,48+2,49+2,49+2,49+2,48+2,48+2,50+2,50+2,50+2,48+2

In [3]:
df.shape

(18278, 104)

In [4]:
df.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=104)

In [5]:
row1=df.loc[3]

In [6]:
row1

sofifa_id                                                200389
player_url    https://sofifa.com/player/200389/jan-oblak/20/...
short_name                                             J. Oblak
long_name                                             Jan Oblak
age                                                          26
                                    ...
lb                                                          NaN
lcb                                                         NaN
cb                                                          NaN
rcb                                                         NaN
rb                                                          NaN
Name: 3, Length: 104, dtype: object

In [7]:
row2=df.iloc[3]

In [8]:
row2

sofifa_id                                                200389
player_url    https://sofifa.com/player/200389/jan-oblak/20/...
short_name                                             J. Oblak
long_name                                             Jan Oblak
age                                                          26
                                    ...
lb                                                          NaN
lcb                                                         NaN
cb                                                          NaN
rcb                                                         NaN
rb                                                          NaN
Name: 3, Length: 104, dtype: object

In [9]:
row1==row2

sofifa_id      True
player_url     True
short_name     True
long_name      True
age            True
              ...
lb            False
lcb           False
cb            False
rcb           False
rb            False
Name: 3, Length: 104, dtype: bool

In [10]:
df.loc[[2,4,3,8]]
# for selecting particular row

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
2,190871,https://sofifa.com/player/190871/neymar-da-sil...,Neymar Jr,Neymar da Silva Santos Junior,27,26-06-1987,175,68,Brazil,Paris Saint-Germain,...,66+3,61+3,61+3,61+3,66+3,61+3,46+3,46+3,46+3,61+3
4,183277,https://sofifa.com/player/183277/eden-hazard/2...,E. Hazard,Eden Hazard,28,28-06-1987,175,74,Belgium,Real Madrid,...,66+3,63+3,63+3,63+3,66+3,61+3,49+3,49+3,49+3,61+3
3,200389,https://sofifa.com/player/200389/jan-oblak/20/...,J. Oblak,Jan Oblak,26,27-06-1987,188,87,Slovenia,Atlético Madrid,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,177003,https://sofifa.com/player/177003/luka-modric/2...,L. Modrić,Luka Modrić,33,02-07-1987,172,66,Croatia,Real Madrid,...,81+3,81+3,81+3,81+3,81+3,79+3,72+3,72+3,72+3,79+3

In [11]:
df.iloc[5:10]
# 10 th excluded

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
5,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,28,29-06-1987,181,70,Belgium,Manchester City,...,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3
6,192448,https://sofifa.com/player/192448/marc-andre-te...,M. ter Stegen,Marc-André ter Stegen,27,30-06-1987,187,85,Germany,FC Barcelona,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,203376,https://sofifa.com/player/203376/virgil-van-di...,V. van Dijk,Virgil van Dijk,27,01-07-1987,193,92,Netherlands,Liverpool,...,79+3,83+3,83+3,83+3,79+3,81+3,87+3,87+3,87+3,81+3
8,177003,https://sofifa.com/player/177003/luka-modric/2...,L. Modrić,Luka Modrić,33,02-07-1987,172,66,Croatia,Real Madrid,...,81+3,81+3,81+3,81+3,81+3,79+3,72+3,72+3,72+3,79+3
9,209331,https://sofifa.com/player/209331/mohamed-salah...,M. Salah,Mohamed Salah Ghaly,27,03-07-1987,175,71,Egypt,Liverpool,...,70+3,67+3,67+3,67+3,70+3,66+3,57+3,57+3,57+3,66+3

In [12]:
df.loc[5:10]
# 10 th included

,sofifa_id,player_url,short_name,long_name,age,dob,height_cm,weight_kg,nationality,club,...,lwb,ldm,cdm,rdm,rwb,lb,lcb,cb,rcb,rb
5,192985,https://sofifa.com/player/192985/kevin-de-bruy...,K. De Bruyne,Kevin De Bruyne,28,29-06-1987,181,70,Belgium,Manchester City,...,77+3,77+3,77+3,77+3,77+3,73+3,66+3,66+3,66+3,73+3
6,192448,https://sofifa.com/player/192448/marc-andre-te...,M. ter Stegen,Marc-André ter Stegen,27,30-06-1987,187,85,Germany,FC Barcelona,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,203376,https://sofifa.com/player/203376/virgil-van-di...,V. van Dijk,Virgil van Dijk,27,01-07-1987,193,92,Netherlands,Liverpool,...,79+3,83+3,83+3,83+3,79+3,81+3,87+3,87+3,87+3,81+3
8,177003,https://sofifa.com/player/177003/luka-modric/2...,L. Modrić,Luka Modrić,33,02-07-1987,172,66,Croatia,Real Madrid,...,81+3,81+3,81+3,81+3,81+3,79+3,72+3,72+3,72+3,79+3
9,209331,https://sofifa.com/player/209331/mohamed-salah...,M. Salah,Mohamed Salah Ghaly,27,03-07-1987,175,71,Egypt,Liverpool,...,70+3,67+3,67+3,67+3,70+3,66+3,57+3,57+3,57+3,66+3
10,231747,https://sofifa.com/player/231747/kylian-mbappe...,K. Mbappé,Kylian Mbappé,20,04-07-1987,178,73,France,Paris Saint-Germain,...,66+3,62+3,62+3,62+3,66+3,63+3,54+3,54+3,54+3,63+3

In [13]:
df.iloc[:,2:7]

,short_name,long_name,age,dob,height_cm
0,L. Messi,Lionel Andrés Messi Cuccittini,32,24-06-1987,170
1,Cristiano Ronaldo,Cristiano Ronaldo dos Santos Aveiro,34,25-06-1987,187
2,Neymar Jr,Neymar da Silva Santos Junior,27,26-06-1987,175
3,J. Oblak,Jan Oblak,26,27-06-1987,188
4,E. Hazard,Eden Hazard,28,28-06-1987,175
...,...,...,...,...,...
18273,Shao Shuai,邵帅,22,10-03-1997,186
18274,Xiao Mingjie,Mingjie Xiao,22,01-01-1997,177
18275,Zhang Wei,张威,19,16-05-2000,186
18276,Wang Haijian,汪海健,18,02-08-2000,185
18277,Pan Ximing,潘喜明,26,11-01-1993,182

In [14]:
df.iloc[[2,5],2:7]

     short_name                      long_name  age         dob  height_cm
2     Neymar Jr  Neymar da Silva Santos Junior   27  26-06-1987        175
5  K. De Bruyne                Kevin De Bruyne   28  29-06-1987        181

In [15]:
df.loc[2:5,['sofifa_id', 'player_url', 'short_name']]

   sofifa_id                                         player_url    short_name
2     190871  https://sofifa.com/player/190871/neymar-da-sil...     Neymar Jr
3     200389  https://sofifa.com/player/200389/jan-oblak/20/...      J. Oblak
4     183277  https://sofifa.com/player/183277/eden-hazard/2...     E. Hazard
5     192985  https://sofifa.com/player/192985/kevin-de-bruy...  K. De Bruyne

In [16]:
df.columns

Index(['sofifa_id', 'player_url', 'short_name', 'long_name', 'age', 'dob',
       'height_cm', 'weight_kg', 'nationality', 'club',
       ...
       'lwb', 'ldm', 'cdm', 'rdm', 'rwb', 'lb', 'lcb', 'cb', 'rcb', 'rb'],
      dtype='object', length=104)